// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://falbhbilcdtpnjapctib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhbGJoYmlsY2R0cG5qYXBjdGliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0OTc5OTAsImV4cCI6MjA3NDA3Mzk5MH0.TKLgVl7j-bdNkJR6mZsIrzqJ0lDOecmZb6GpChQ1r8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});